language: python

python:
- '3.5'

install: python setup.py develop

script: true

# test pypi
#deploy:
#  provider: pypi
#  server: https://test.pypi.org/legacy/
#  user: python-egnyte
#  password:
#    secure: "DJkgHOKvYBI7CfbnYk1D7buShngpyXyj7UIjTMugu/eqLsroN5uA38uMkdVsaiGFEeBpToBj6k56XJn4iYJPFXWZpoh5CDmQH990tRrpBaaMacVhvDtl1So2cGCHffKDZtNaFuRMcy0TVEPjaV+H1Xo4HyIyTFwk/QD2Ly0kW86tFy8ud/uwroutYFXH6Ii3Ove1WaFyiFlnGAUgRBGJC9JuigC9WpHWQ0k8/NPhv+6SbxYeU8SsmJYbkDF9vpWF+UoTlia2kTow9SvnVT+B5gBfVwRr0iq0u7zb5R+Pop9ROeRe/stDAc78h5ugQDPTlUgZcSgKGJd+UxKyt0oxK1x++2EnL0Y5uInwapakxt6FL/4SLaTJSo0IbvmXR+Z6xygTo6HLd+5M+2yt76rifqn6CFekg+utWCQ12I0KlpYdQhfbkuMSmRR+yAbaGTkHVUoPwrcoL6ZMUWgod3wSTFgPe1xotBQYsMjchxo0euAUWU7HUqkcINJWSroX1ClYq+bfo7CF/2eK1qy8kIEp67AAUyyOJDewybtX5t8aE4exjAzsZoBgMil0mnq8XlIH78jL38GAbd/mpeYqUbdIBq3rOK42i6G9pPzHAmItgzWXGMdeo0aqTZUxOwRxvYLTGLRZ0g12QyByAY6N12BIpL34jumDAB0IFsWv38C3iCw="

deploy:
  provider: pypi
  user: python-egnyte
  password:
    secure: "bMOHsUnrDpl7m4AZs9h2yXsXYNvIxJZvRfk2gAf4h0KzzcxuARef4Q78Z1Phrx1ryAvm4sDtP2A4E4j3jbyDpGmhJhRUZlbzMgeF1VVIlO886o8SM66EIFD/1766DK8m/DXksvWKd+H/BjV/Na00L3mMvU7CVVEtKVNRszbCfZGvimKfhWRSueUFrt0BtIitZ5Q7OIPf2T/+9jlkaeHISGVF0vDQ0SNTCwri237QKu/zmZYKV29gPX/rZQnk+3PdfbRmsKkWdbHsnFOPwPCs4UOs7pkWrK2eXnOKqJb0mFKQj92c2fVNqh3PQmBW1SGtNNhR75OsQ9G9DCVS/UmQtmR1XietcL+6ccwiBFpQLDq3iHYu5KRewRgcWrpFTL0ns+xS6mZUQBxPCcHn7H0yYnkrVwRrT424tnQRPg/R3mSbYfjA1B2O9W7MIGMENp3zUjCVdYt+0F+Vq5O2sALs1CeeRHdXQ2S2MfSMoL4vDbc2e2c8eIYdMw4oAGApOwCGhFjn8P47zNu80n9PnVbGfa1IcR2nOpM2zu1xkori5S72ZuDuCml9feAWKaVKYxeex02Fl1VUJUEYPy1+5LXbSPl1B9HyJ9DsN7k+cZ16qxT1ub46IsFpqIxA9pzQW4hgIQs5n8WDYZj3WnYtUe+tLrjdNFRSqco388oV50IcFJo="
  on:
    tags: true
